From 238ed04bff72594deb8c73b3f20ba1a96a5f29a4 Mon Sep 17 00:00:00 2001
From: Alex Van Damme <atv@google.com>
Date: Thu, 15 May 2025 17:15:41 -0700
Subject: [PATCH 6/6] Use num_failed for exit code

---
 cocotb/cocotb_wrapper.py | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/cocotb/cocotb_wrapper.py b/cocotb/cocotb_wrapper.py
index 3929519..ce392a9 100644
--- a/cocotb/cocotb_wrapper.py
+++ b/cocotb/cocotb_wrapper.py
@@ -14,7 +14,9 @@
 
 import argparse
 import cocotb_tools
+import sys
 from cocotb_tools.runner import get_runner
+from cocotb_tools.check_results import get_results
 
 
 cocotb_build_flags = [
@@ -166,7 +168,6 @@ def cocotb_argument_parser():
 
     return parser
 
-
 if __name__ == "__main__":
     parser = cocotb_argument_parser()
     args = parser.parse_args()
@@ -189,3 +190,5 @@ if __name__ == "__main__":
     runner = get_runner(args.sim)
     runner.build(**build_flags)
     results_xml = runner.test(**test_flags)
+    (num_tests, num_failed) = get_results(results_xml)
+    sys.exit(num_failed)
-- 
2.49.0.1101.gccaa498523-goog

